### PR TITLE
Xposition issues #33 

### PR DESCRIPTION
**Pull request by ablodge**

### CODE REVIEW

**Comment by nschneid** [comment]
Does this fix it locally for you?

**Comment by ablodge** [comment]
How do you set Supersenses as roots (i.e. CIrcumstance, Configuration, Participant) ?

**Comment by nschneid** [comment]
If you have a supersense with no parent, it should be a root.

**Comment by ablodge** [comment]
That isn't working locally

**Comment by ablodge** [comment]
See https://github.com/nert-gu/Xposition/blob/ab2dbdc848df2d45829ed2e9165f469dc59d261b/wiki/plugins/metadata/templates/supersense_list.html

**Comment by ablodge** [comment]
Please review

**Pull request merged**
