### PR TITLE
Wiki profiler

### PR DESCRIPTION
**Pull request by ablodge**
#96 Speed up article loading

### CODE REVIEW

**Comment by nschneid** [comment]
OK, I have some concerns about [cache_page](https://docs.djangoproject.com/en/2.0/topics/cache/):

1. It is being used with a 15-minute timeout—so this only caches recently loaded pages, right? I don't know how useful this is in general unless a user is going back and forth between pages in a session. A longer-term cache (say, for a week or longer) may be useful as long as there's a way to ensure that the cached version won't be out-of-date when content is changed.
2. When an article is edited, will the outdated version persist until the cache timeout? This would be confusing. Perhaps there's a way to invalidate the cached version.
3. https://www.technomancy.org/python/django-cache_page-useless/ suggests that session-specific info (such as the username in the navbar) will leak across sessions. Maybe what is needed is [template fragment caching](https://docs.djangoproject.com/en/2.0/topics/cache/#template-fragment-caching) to target the key slow bits that we know are session-invariant—the article, corpus display table, lists of links from a database query. (We have to be careful about permissions, too: if articles can be made visible only to certain users, the cache has to respect that.)

**Comment by ablodge** [comment]
2: you can test this by opening the same article in two tabs, editing one and refreshing the other to see if it loads the change. It works fine.

3: For reference, template fragment caching is explained [here](https://docs.djangoproject.com/en/2.0/topics/cache/#template-fragment-caching)

**Comment by ablodge** [comment]
Alright, I'll remove caching from the branch. We can add template fragment caching as a separate issue.

**Comment by ablodge** [comment]
Removes list of usages for-loop on languages page, adds comments for later caching articles.

**Pull request merged**
